version: "2"
services:
  zookeeper:
    image: confluent/zookeeper
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"

  kafka:
    image: edf5af24f630
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9999:9999"
    links:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_HOST_NAME: "192.168.99.100"
    
  rest-proxy:
    image: confluent/rest-proxy
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    ports:
      - "8082:8082"
    links:
      - zookeeper
      - kafka
      - schema-registry
    environment:
      RP_ZOOKEEPER_CONNECT: "zookeeper:2181"
      RP_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
    
  schema-registry:
    image: confluent/schema-registry
    depends_on:
      - kafka
      - zookeeper
    links:
      - kafka
      - zookeeper
    ports:
      - "8081:8081"
    environment:
      SR_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"

  kafka-manager:
    image: sheepkiller/kafka-manager
    depends_on:
      - kafka
      - zookeeper
    links:
      - kafka
      - zookeeper
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "letmein"
      KM_ARGS: "-Djava.net.preferIPv4Stack=true"
    

  elasticsearch-int:
    image: elasticsearch
    ports:
      - 9200:9200

  kibana-int:
    image: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch-int:9200"
    links:
      - elasticsearch-int