version: "2"
services:
  zookeeper:
    image: confluent/zookeeper
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"

  kafka:
    image: confluent/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    
  rest-proxy:
    image: confluent/rest-proxy
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    ports:
      - "8082:8082"
    links:
      - zookeeper
      - kafka
      - schema-registry
    environment:
      RP_ZOOKEEPER_CONNECT: "zookeeper:2181"
      RP_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
    
  schema-registry:
    image: confluent/schema-registry
    depends_on:
      - kafka
      - zookeeper
    links:
      - kafka
      - zookeeper
    ports:
      - "8081:8081"
    environment:
      SR_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
    

  elasticsearch-int:
    image: elasticsearch
    ports:
      - 9200:9200

  kibana-int:
    image: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch-int:9200"
    links:
      - elasticsearch-int